### ISSUE TITLE
Angular 1.5 component support

### ISSUE THREAD

**Issue by jabyrd3** [mradionov/tleaf#6]
This would be super nice to have for us.

Thanks for tleaf, it's nice to get the boilerplate out of the way.

**Comment by mradionov** [comment]
Glad to here that it is useful! I'll work on adding a component support, but it might take some time because I myself did not have a chance to use and test components. Thanks!

**Comment by mradionov** [comment]
I finally was able to add Angular 1.5 component support, version [0.2.0](https://www.npmjs.com/package/tleaf) now available on npm. If you have any issues or suggestions feel free to open another issue. Thanks!
